# key: Space
# mods: Shift,
# chars: "\x5c\x08 "
#
#key_bindings: { key: Return,   mods: Control|Shift, action: SpawnNewInstance }

[font]
size = 9

[font.normal] 
family = "Hack"
# family: Monospace
# family: Source Code Pro
# family: Iosevka Term Nerd Font
# family: Iosevka Nerd Font Mono
# family: Iosevka Nerd Font
# family: Iosevka Term Nerd Font Mono
# family: Iosevka Term Nerd



# Doom One Colors 
[colors]

[colors.primary]
background = '0x282c34'
foreground = '0xbbc2cf'

[colors.normal] 
black = '0x282c34'
red = '0xff6c6b'
green = '0x98be65'
yellow = '0xecbe7b'
blue = '0x51afef'
magenta = '0xc678dd'
cyan = '0x46d9ff'
white = '0xbbc2cf'

# doom_dark: &doom_dark
#   primary:
#     foreground: '#bbc2cf'
#     background: "#282c34"
#   cursor:
#     cursor: '#51afef'
#     text: '#282c34'
#   normal:
#     black: "#282c34"
#     red: "#ff6c6b"
#     green: "#98be65"
#     yellow: "#ecbe7b"
#     blue: "#51afef"
#     magenta: "#a9a1e1"
#     cyan: "#46d9ff"
#     white: "#bbc2cf"
#   bright:
#     black: "#3f444a"
#     red: "#ff6c6b"
#     green: "#98be65"
#     yellow: "#da8548"
#     blue: "#51afef"
#     magenta: "#a9a1e1"
#     cyan: "#46d9ff"
#     white: "#efefef"
# colors: *doom_dark


# Dracula Colors 
# colors:
#   primary:
#     background: '0x282a36'
#     foreground: '0xf8f8f2'
#   normal:
#     black:   '0x000000'
#     red:     '0xff5555'
#     green:   '0x50fa7b'
#     yellow:  '0xf1fa8c'
#     blue:    '0xbd93f9'
#     magenta: '0xff79c6'
#     cyan:    '0x8be9fd'
#     white:   '0xbbbbbb'
#   bright:
#     black:   '0x555555'
#     red:     '0xff5555'
#     green:   '0x50fa7b'
#     yellow:  '0xf1fa8c'
#     blue:    '0xcaa9fa'
#     magenta: '0xff79c6'
#     cyan:    '0x8be9fd'
#     white:   '0xffffff'
